version: "3.8"

services:
  postgres:
    container_name: grupo-musica-postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
#    volumes:
#      - ./db/postgres:/var/lib/postgresql/data
